name: Full MLOps Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run data pipeline
        run: |
          python pipeline/data_pipeline.py
      - name: Train model
        run: |
          python model/train.py
      - name: Start API (background)
        run: |
          uvicorn api.main:app --host 0.0.0.0 --port 8000 &
          sleep 10
      - name: Run all tests
        run: |
          pytest --cov=./ --cov-report=xml 